/////////////////////////////////////////////////////////////
// cxr_test.h
//
// This file was generated by CXR, the literal string encryptor.
// CXR, Copyright 2002, Smaller Animals Software, Inc., all rights reserved.
//
// Please do not edit this file. Any changes here will be overwritten on the next compile.
// If you wish to make changes to a string, please edit:
//     test.cxr
//

/////////////////////////////////////////////////////////////

#pragma once
#include "cxr_inc.h"

// cxr 적용 테스트입니당

///////////////////////////
#ifdef _USING_CXR
#define STR_CXRTEST1 	_CXR("\x8c\x83\x8d\x85\x8a\x89\x86\x8d\x8d\x81\x86\x85\x81\x8a\x85\x8e\x83\x86\x82\x8a\x81\x8a\x81\x8d\x86\x83\x8f\x83\x8f\x80\x8d\x87\x8a\x88\x83\x89\x89\x8f\x85\x83\x8d\x8a\x81\x89\x8c\x8b\x8b\x80\x82\x84\x81\x81\x88\x84\x81\x81\x8c\x89\x86\x83\x8f\x84\x85\x8e\x8c\x8c")
#else
#define STR_CXRTEST1 _CXR("Your all bases are belong to us.")
#endif

///////////////////////////
#ifdef _USING_CXR
#define STR_CXRTEST2 	_CXR("\x85\x80\x85\x86\x81\x84\x8e\x8a\x8b\x89\x86\x86\x8d\x84\x8c\x87\x8f\x8b\x82\x81")// 디파인 뒤에 주석이 달린 경우를 테스트
#else
#define STR_CXRTEST2 _CXR("It's You!")// 디파인 뒤에 주석이 달린 경우를 테스트
#endif

///////////////////////////
#ifdef _USING_CXR
#define STR_CXRTEST3 	_CXR("\x8f\x84\x85\x88\x81\x8c\x8f\x84\x86\x87")		// 디파인 뒤에 공백을 두고 주석이 달린 경우를 테스트
#else
#define STR_CXRTEST3 _CXR("Aye.")		// 디파인 뒤에 공백을 두고 주석이 달린 경우를 테스트
#endif


