/////////////////////////////////////////////////////////////
// cxr_test.h
//
// This file was generated by CXR, the literal string encryptor.
// CXR, Copyright 2002, Smaller Animals Software, Inc., all rights reserved.
//
// Please do not edit this file. Any changes here will be overwritten on the next compile.
// If you wish to make changes to a string, please edit:
//     test.cxr
//

/////////////////////////////////////////////////////////////

#pragma once
#include "cxr_inc.h"

// cxr 적용 테스트입니당

///////////////////////////
#ifdef _USING_CXR
#define STR_CXRTEST1 	_CXR("\x88\x80\x85\x8f\x8a\x83\x83\x84\x80\x86\x89\x8f\x83\x8a\x87\x80\x89\x81\x8b\x8a\x8e\x8a\x8b\x8f\x83\x80\x8d\x83\x8d\x80\x83\x84\x8d\x8d\x88\x8e\x8c\x81\x87\x84\x8d\x88\x81\x8c\x88\x8b\x8a\x82\x82\x8f\x85\x8a\x80\x86\x8e\x85\x82\x85\x8e\x84\x8f\x89\x88\x80\x85\x84")
#else
#define STR_CXRTEST1 _CXR("Your all bases are belong to us.")
#endif

///////////////////////////
#ifdef _USING_CXR
#define STR_CXRTEST2 	_CXR("\x8a\x8b\x84\x88\x8b\x8f\x82\x82\x8e\x80\x8a\x85\x8d\x8c\x84\x83\x8a\x85\x8a\x81")// 디파인 뒤에 주석이 달린 경우를 테스트
#else
#define STR_CXRTEST2 _CXR("It's You!")// 디파인 뒤에 주석이 달린 경우를 테스트
#endif

///////////////////////////
#ifdef _USING_CXR
#define STR_CXRTEST3 	_CXR("\x82\x89\x8d\x84\x81\x84\x84\x8a\x89\x8d")		// 디파인 뒤에 공백을 두고 주석이 달린 경우를 테스트
#else
#define STR_CXRTEST3 _CXR("Aye.")		// 디파인 뒤에 공백을 두고 주석이 달린 경우를 테스트
#endif


